# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoCurrenciesApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoCurrenciesApp
  pod 'Alamofire'
  pod 'RxAlamofire'
  pod 'RxCocoa'
  pod 'AlamofireObjectMapper'

end